namespace Smab.Helpers;

public static partial class Utf16Chars {
	public static partial class BoxDrawing {
		public static readonly char BOX_DRAWINGS_LIGHT_HORIZONTAL                         = '─'; // (U+2500) feff2500
		public static readonly char BOX_DRAWINGS_HEAVY_HORIZONTAL                         = '━'; // (U+2501) feff2501
		public static readonly char BOX_DRAWINGS_LIGHT_VERTICAL                           = '│'; // (U+2502) feff2502
		public static readonly char BOX_DRAWINGS_HEAVY_VERTICAL                           = '┃'; // (U+2503) feff2503
		public static readonly char BOX_DRAWINGS_LIGHT_TRIPLE_DASH_HORIZONTAL             = '┄'; // (U+2504) feff2504
		public static readonly char BOX_DRAWINGS_HEAVY_TRIPLE_DASH_HORIZONTAL             = '┅'; // (U+2505) feff2505
		public static readonly char BOX_DRAWINGS_LIGHT_TRIPLE_DASH_VERTICAL               = '┆'; // (U+2506) feff2506
		public static readonly char BOX_DRAWINGS_HEAVY_TRIPLE_DASH_VERTICAL               = '┇'; // (U+2507) feff2507
		public static readonly char BOX_DRAWINGS_LIGHT_QUADRUPLE_DASH_HORIZONTAL          = '┈'; // (U+2508) feff2508
		public static readonly char BOX_DRAWINGS_HEAVY_QUADRUPLE_DASH_HORIZONTAL          = '┉'; // (U+2509) feff2509
		public static readonly char BOX_DRAWINGS_LIGHT_QUADRUPLE_DASH_VERTICAL            = '┊'; // (U+250A) feff250a
		public static readonly char BOX_DRAWINGS_HEAVY_QUADRUPLE_DASH_VERTICAL            = '┋'; // (U+250B) feff250b
		public static readonly char BOX_DRAWINGS_LIGHT_DOWN_AND_RIGHT                     = '┌'; // (U+250C) feff250c
		public static readonly char BOX_DRAWINGS_DOWN_LIGHT_AND_RIGHT_HEAVY               = '┍'; // (U+250D) feff250d
		public static readonly char BOX_DRAWINGS_DOWN_HEAVY_AND_RIGHT_LIGHT               = '┎'; // (U+250E) feff250e
		public static readonly char BOX_DRAWINGS_HEAVY_DOWN_AND_RIGHT                     = '┏'; // (U+250F) feff250f
		public static readonly char BOX_DRAWINGS_LIGHT_DOWN_AND_LEFT                      = '┐'; // (U+2510) feff2510
		public static readonly char BOX_DRAWINGS_DOWN_LIGHT_AND_LEFT_HEAVY                = '┑'; // (U+2511) feff2511
		public static readonly char BOX_DRAWINGS_DOWN_HEAVY_AND_LEFT_LIGHT                = '┒'; // (U+2512) feff2512
		public static readonly char BOX_DRAWINGS_HEAVY_DOWN_AND_LEFT                      = '┓'; // (U+2513) feff2513
		public static readonly char BOX_DRAWINGS_LIGHT_UP_AND_RIGHT                       = '└'; // (U+2514) feff2514
		public static readonly char BOX_DRAWINGS_UP_LIGHT_AND_RIGHT_HEAVY                 = '┕'; // (U+2515) feff2515
		public static readonly char BOX_DRAWINGS_UP_HEAVY_AND_RIGHT_LIGHT                 = '┖'; // (U+2516) feff2516
		public static readonly char BOX_DRAWINGS_HEAVY_UP_AND_RIGHT                       = '┗'; // (U+2517) feff2517
		public static readonly char BOX_DRAWINGS_LIGHT_UP_AND_LEFT                        = '┘'; // (U+2518) feff2518
		public static readonly char BOX_DRAWINGS_UP_LIGHT_AND_LEFT_HEAVY                  = '┙'; // (U+2519) feff2519
		public static readonly char BOX_DRAWINGS_UP_HEAVY_AND_LEFT_LIGHT                  = '┚'; // (U+251A) feff251a
		public static readonly char BOX_DRAWINGS_HEAVY_UP_AND_LEFT                        = '┛'; // (U+251B) feff251b
		public static readonly char BOX_DRAWINGS_LIGHT_VERTICAL_AND_RIGHT                 = '├'; // (U+251C) feff251c
		public static readonly char BOX_DRAWINGS_VERTICAL_LIGHT_AND_RIGHT_HEAVY           = '┝'; // (U+251D) feff251d
		public static readonly char BOX_DRAWINGS_UP_HEAVY_AND_RIGHT_DOWN_LIGHT            = '┞'; // (U+251E) feff251e
		public static readonly char BOX_DRAWINGS_DOWN_HEAVY_AND_RIGHT_UP_LIGHT            = '┟'; // (U+251F) feff251f
		public static readonly char BOX_DRAWINGS_VERTICAL_HEAVY_AND_RIGHT_LIGHT           = '┠'; // (U+2520) feff2520
		public static readonly char BOX_DRAWINGS_DOWN_LIGHT_AND_RIGHT_UP_HEAVY            = '┡'; // (U+2521) feff2521
		public static readonly char BOX_DRAWINGS_UP_LIGHT_AND_RIGHT_DOWN_HEAVY            = '┢'; // (U+2522) feff2522
		public static readonly char BOX_DRAWINGS_HEAVY_VERTICAL_AND_RIGHT                 = '┣'; // (U+2523) feff2523
		public static readonly char BOX_DRAWINGS_LIGHT_VERTICAL_AND_LEFT                  = '┤'; // (U+2524) feff2524
		public static readonly char BOX_DRAWINGS_VERTICAL_LIGHT_AND_LEFT_HEAVY            = '┥'; // (U+2525) feff2525
		public static readonly char BOX_DRAWINGS_UP_HEAVY_AND_LEFT_DOWN_LIGHT             = '┦'; // (U+2526) feff2526
		public static readonly char BOX_DRAWINGS_DOWN_HEAVY_AND_LEFT_UP_LIGHT             = '┧'; // (U+2527) feff2527
		public static readonly char BOX_DRAWINGS_VERTICAL_HEAVY_AND_LEFT_LIGHT            = '┨'; // (U+2528) feff2528
		public static readonly char BOX_DRAWINGS_DOWN_LIGHT_AND_LEFT_UP_HEAVY             = '┩'; // (U+2529) feff2529
		public static readonly char BOX_DRAWINGS_UP_LIGHT_AND_LEFT_DOWN_HEAVY             = '┪'; // (U+252A) feff252a
		public static readonly char BOX_DRAWINGS_HEAVY_VERTICAL_AND_LEFT                  = '┫'; // (U+252B) feff252b
		public static readonly char BOX_DRAWINGS_LIGHT_DOWN_AND_HORIZONTAL                = '┬'; // (U+252C) feff252c
		public static readonly char BOX_DRAWINGS_LEFT_HEAVY_AND_RIGHT_DOWN_LIGHT          = '┭'; // (U+252D) feff252d
		public static readonly char BOX_DRAWINGS_RIGHT_HEAVY_AND_LEFT_DOWN_LIGHT          = '┮'; // (U+252E) feff252e
		public static readonly char BOX_DRAWINGS_DOWN_LIGHT_AND_HORIZONTAL_HEAVY          = '┯'; // (U+252F) feff252f
		public static readonly char BOX_DRAWINGS_DOWN_HEAVY_AND_HORIZONTAL_LIGHT          = '┰'; // (U+2530) feff2530
		public static readonly char BOX_DRAWINGS_RIGHT_LIGHT_AND_LEFT_DOWN_HEAVY          = '┱'; // (U+2531) feff2531
		public static readonly char BOX_DRAWINGS_LEFT_LIGHT_AND_RIGHT_DOWN_HEAVY          = '┲'; // (U+2532) feff2532
		public static readonly char BOX_DRAWINGS_HEAVY_DOWN_AND_HORIZONTAL                = '┳'; // (U+2533) feff2533
		public static readonly char BOX_DRAWINGS_LIGHT_UP_AND_HORIZONTAL                  = '┴'; // (U+2534) feff2534
		public static readonly char BOX_DRAWINGS_LEFT_HEAVY_AND_RIGHT_UP_LIGHT            = '┵'; // (U+2535) feff2535
		public static readonly char BOX_DRAWINGS_RIGHT_HEAVY_AND_LEFT_UP_LIGHT            = '┶'; // (U+2536) feff2536
		public static readonly char BOX_DRAWINGS_UP_LIGHT_AND_HORIZONTAL_HEAVY            = '┷'; // (U+2537) feff2537
		public static readonly char BOX_DRAWINGS_UP_HEAVY_AND_HORIZONTAL_LIGHT            = '┸'; // (U+2538) feff2538
		public static readonly char BOX_DRAWINGS_RIGHT_LIGHT_AND_LEFT_UP_HEAVY            = '┹'; // (U+2539) feff2539
		public static readonly char BOX_DRAWINGS_LEFT_LIGHT_AND_RIGHT_UP_HEAVY            = '┺'; // (U+253A) feff253a
		public static readonly char BOX_DRAWINGS_HEAVY_UP_AND_HORIZONTAL                  = '┻'; // (U+253B) feff253b
		public static readonly char BOX_DRAWINGS_LIGHT_VERTICAL_AND_HORIZONTAL            = '┼'; // (U+253C) feff253c
		public static readonly char BOX_DRAWINGS_LEFT_HEAVY_AND_RIGHT_VERTICAL_LIGHT      = '┽'; // (U+253D) feff253d
		public static readonly char BOX_DRAWINGS_RIGHT_HEAVY_AND_LEFT_VERTICAL_LIGHT      = '┾'; // (U+253E) feff253e
		public static readonly char BOX_DRAWINGS_VERTICAL_LIGHT_AND_HORIZONTAL_HEAVY      = '┿'; // (U+253F) feff253f
		public static readonly char BOX_DRAWINGS_UP_HEAVY_AND_DOWN_HORIZONTAL_LIGHT       = '╀'; // (U+2540) feff2540
		public static readonly char BOX_DRAWINGS_DOWN_HEAVY_AND_UP_HORIZONTAL_LIGHT       = '╁'; // (U+2541) feff2541
		public static readonly char BOX_DRAWINGS_VERTICAL_HEAVY_AND_HORIZONTAL_LIGHT      = '╂'; // (U+2542) feff2542
		public static readonly char BOX_DRAWINGS_LEFT_UP_HEAVY_AND_RIGHT_DOWN_LIGHT       = '╃'; // (U+2543) feff2543
		public static readonly char BOX_DRAWINGS_RIGHT_UP_HEAVY_AND_LEFT_DOWN_LIGHT       = '╄'; // (U+2544) feff2544
		public static readonly char BOX_DRAWINGS_LEFT_DOWN_HEAVY_AND_RIGHT_UP_LIGHT       = '╅'; // (U+2545) feff2545
		public static readonly char BOX_DRAWINGS_RIGHT_DOWN_HEAVY_AND_LEFT_UP_LIGHT       = '╆'; // (U+2546) feff2546
		public static readonly char BOX_DRAWINGS_DOWN_LIGHT_AND_UP_HORIZONTAL_HEAVY       = '╇'; // (U+2547) feff2547
		public static readonly char BOX_DRAWINGS_UP_LIGHT_AND_DOWN_HORIZONTAL_HEAVY       = '╈'; // (U+2548) feff2548
		public static readonly char BOX_DRAWINGS_RIGHT_LIGHT_AND_LEFT_VERTICAL_HEAVY      = '╉'; // (U+2549) feff2549
		public static readonly char BOX_DRAWINGS_LEFT_LIGHT_AND_RIGHT_VERTICAL_HEAVY      = '╊'; // (U+254A) feff254a
		public static readonly char BOX_DRAWINGS_HEAVY_VERTICAL_AND_HORIZONTAL            = '╋'; // (U+254B) feff254b
		public static readonly char BOX_DRAWINGS_LIGHT_DOUBLE_DASH_HORIZONTAL             = '╌'; // (U+254C) feff254c
		public static readonly char BOX_DRAWINGS_HEAVY_DOUBLE_DASH_HORIZONTAL             = '╍'; // (U+254D) feff254d
		public static readonly char BOX_DRAWINGS_LIGHT_DOUBLE_DASH_VERTICAL               = '╎'; // (U+254E) feff254e
		public static readonly char BOX_DRAWINGS_HEAVY_DOUBLE_DASH_VERTICAL               = '╏'; // (U+254F) feff254f
		public static readonly char BOX_DRAWINGS_DOUBLE_HORIZONTAL                        = '═'; // (U+2550) feff2550
		public static readonly char BOX_DRAWINGS_DOUBLE_VERTICAL                          = '║'; // (U+2551) feff2551
		public static readonly char BOX_DRAWINGS_DOWN_SINGLE_AND_RIGHT_DOUBLE             = '╒'; // (U+2552) feff2552
		public static readonly char BOX_DRAWINGS_DOWN_DOUBLE_AND_RIGHT_SINGLE             = '╓'; // (U+2553) feff2553
		public static readonly char BOX_DRAWINGS_DOUBLE_DOWN_AND_RIGHT                    = '╔'; // (U+2554) feff2554
		public static readonly char BOX_DRAWINGS_DOWN_SINGLE_AND_LEFT_DOUBLE              = '╕'; // (U+2555) feff2555
		public static readonly char BOX_DRAWINGS_DOWN_DOUBLE_AND_LEFT_SINGLE              = '╖'; // (U+2556) feff2556
		public static readonly char BOX_DRAWINGS_DOUBLE_DOWN_AND_LEFT                     = '╗'; // (U+2557) feff2557
		public static readonly char BOX_DRAWINGS_UP_SINGLE_AND_RIGHT_DOUBLE               = '╘'; // (U+2558) feff2558
		public static readonly char BOX_DRAWINGS_UP_DOUBLE_AND_RIGHT_SINGLE               = '╙'; // (U+2559) feff2559
		public static readonly char BOX_DRAWINGS_DOUBLE_UP_AND_RIGHT                      = '╚'; // (U+255A) feff255a
		public static readonly char BOX_DRAWINGS_UP_SINGLE_AND_LEFT_DOUBLE                = '╛'; // (U+255B) feff255b
		public static readonly char BOX_DRAWINGS_UP_DOUBLE_AND_LEFT_SINGLE                = '╜'; // (U+255C) feff255c
		public static readonly char BOX_DRAWINGS_DOUBLE_UP_AND_LEFT                       = '╝'; // (U+255D) feff255d
		public static readonly char BOX_DRAWINGS_VERTICAL_SINGLE_AND_RIGHT_DOUBLE         = '╞'; // (U+255E) feff255e
		public static readonly char BOX_DRAWINGS_VERTICAL_DOUBLE_AND_RIGHT_SINGLE         = '╟'; // (U+255F) feff255f
		public static readonly char BOX_DRAWINGS_DOUBLE_VERTICAL_AND_RIGHT                = '╠'; // (U+2560) feff2560
		public static readonly char BOX_DRAWINGS_VERTICAL_SINGLE_AND_LEFT_DOUBLE          = '╡'; // (U+2561) feff2561
		public static readonly char BOX_DRAWINGS_VERTICAL_DOUBLE_AND_LEFT_SINGLE          = '╢'; // (U+2562) feff2562
		public static readonly char BOX_DRAWINGS_DOUBLE_VERTICAL_AND_LEFT                 = '╣'; // (U+2563) feff2563
		public static readonly char BOX_DRAWINGS_DOWN_SINGLE_AND_HORIZONTAL_DOUBLE        = '╤'; // (U+2564) feff2564
		public static readonly char BOX_DRAWINGS_DOWN_DOUBLE_AND_HORIZONTAL_SINGLE        = '╥'; // (U+2565) feff2565
		public static readonly char BOX_DRAWINGS_DOUBLE_DOWN_AND_HORIZONTAL               = '╦'; // (U+2566) feff2566
		public static readonly char BOX_DRAWINGS_UP_SINGLE_AND_HORIZONTAL_DOUBLE          = '╧'; // (U+2567) feff2567
		public static readonly char BOX_DRAWINGS_UP_DOUBLE_AND_HORIZONTAL_SINGLE          = '╨'; // (U+2568) feff2568
		public static readonly char BOX_DRAWINGS_DOUBLE_UP_AND_HORIZONTAL                 = '╩'; // (U+2569) feff2569
		public static readonly char BOX_DRAWINGS_VERTICAL_SINGLE_AND_HORIZONTAL_DOUBLE    = '╪'; // (U+256A) feff256a
		public static readonly char BOX_DRAWINGS_VERTICAL_DOUBLE_AND_HORIZONTAL_SINGLE    = '╫'; // (U+256B) feff256b
		public static readonly char BOX_DRAWINGS_DOUBLE_VERTICAL_AND_HORIZONTAL           = '╬'; // (U+256C) feff256c
		public static readonly char BOX_DRAWINGS_LIGHT_ARC_DOWN_AND_RIGHT                 = '╭'; // (U+256D) feff256d
		public static readonly char BOX_DRAWINGS_LIGHT_ARC_DOWN_AND_LEFT                  = '╮'; // (U+256E) feff256e
		public static readonly char BOX_DRAWINGS_LIGHT_ARC_UP_AND_LEFT                    = '╯'; // (U+256F) feff256f
		public static readonly char BOX_DRAWINGS_LIGHT_ARC_UP_AND_RIGHT                   = '╰'; // (U+2570) feff2570
		public static readonly char BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_RIGHT_TO_LOWER_LEFT = '╱'; // (U+2571) feff2571
		public static readonly char BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_LEFT_TO_LOWER_RIGHT = '╲'; // (U+2572) feff2572
		public static readonly char BOX_DRAWINGS_LIGHT_DIAGONAL_CROSS                     = '╳'; // (U+2573) feff2573
		public static readonly char BOX_DRAWINGS_LIGHT_LEFT                               = '╴'; // (U+2574) feff2574
		public static readonly char BOX_DRAWINGS_LIGHT_UP                                 = '╵'; // (U+2575) feff2575
		public static readonly char BOX_DRAWINGS_LIGHT_RIGHT                              = '╶'; // (U+2576) feff2576
		public static readonly char BOX_DRAWINGS_LIGHT_DOWN                               = '╷'; // (U+2577) feff2577
		public static readonly char BOX_DRAWINGS_HEAVY_LEFT                               = '╸'; // (U+2578) feff2578
		public static readonly char BOX_DRAWINGS_HEAVY_UP                                 = '╹'; // (U+2579) feff2579
		public static readonly char BOX_DRAWINGS_HEAVY_RIGHT                              = '╺'; // (U+257A) feff257a
		public static readonly char BOX_DRAWINGS_HEAVY_DOWN                               = '╻'; // (U+257B) feff257b
		public static readonly char BOX_DRAWINGS_LIGHT_LEFT_AND_HEAVY_RIGHT               = '╼'; // (U+257C) feff257c
		public static readonly char BOX_DRAWINGS_LIGHT_UP_AND_HEAVY_DOWN                  = '╽'; // (U+257D) feff257d
		public static readonly char BOX_DRAWINGS_HEAVY_LEFT_AND_LIGHT_RIGHT               = '╾'; // (U+257E) feff257e
		public static readonly char BOX_DRAWINGS_HEAVY_UP_AND_LIGHT_DOWN                  = '╿'; // (U+257F) feff257f

		public static readonly char LIGHT_HORIZONTAL                         = BOX_DRAWINGS_LIGHT_HORIZONTAL                         ;
		public static readonly char HEAVY_HORIZONTAL                         = BOX_DRAWINGS_HEAVY_HORIZONTAL                         ;
		public static readonly char LIGHT_VERTICAL                           = BOX_DRAWINGS_LIGHT_VERTICAL                           ;
		public static readonly char HEAVY_VERTICAL                           = BOX_DRAWINGS_HEAVY_VERTICAL                           ;
		public static readonly char LIGHT_TRIPLE_DASH_HORIZONTAL             = BOX_DRAWINGS_LIGHT_TRIPLE_DASH_HORIZONTAL             ;
		public static readonly char HEAVY_TRIPLE_DASH_HORIZONTAL             = BOX_DRAWINGS_HEAVY_TRIPLE_DASH_HORIZONTAL             ;
		public static readonly char LIGHT_TRIPLE_DASH_VERTICAL               = BOX_DRAWINGS_LIGHT_TRIPLE_DASH_VERTICAL               ;
		public static readonly char HEAVY_TRIPLE_DASH_VERTICAL               = BOX_DRAWINGS_HEAVY_TRIPLE_DASH_VERTICAL               ;
		public static readonly char LIGHT_QUADRUPLE_DASH_HORIZONTAL          = BOX_DRAWINGS_LIGHT_QUADRUPLE_DASH_HORIZONTAL          ;
		public static readonly char HEAVY_QUADRUPLE_DASH_HORIZONTAL          = BOX_DRAWINGS_HEAVY_QUADRUPLE_DASH_HORIZONTAL          ;
		public static readonly char LIGHT_QUADRUPLE_DASH_VERTICAL            = BOX_DRAWINGS_LIGHT_QUADRUPLE_DASH_VERTICAL            ;
		public static readonly char HEAVY_QUADRUPLE_DASH_VERTICAL            = BOX_DRAWINGS_HEAVY_QUADRUPLE_DASH_VERTICAL            ;
		public static readonly char LIGHT_DOWN_AND_RIGHT                     = BOX_DRAWINGS_LIGHT_DOWN_AND_RIGHT                     ;
		public static readonly char DOWN_LIGHT_AND_RIGHT_HEAVY               = BOX_DRAWINGS_DOWN_LIGHT_AND_RIGHT_HEAVY               ;
		public static readonly char DOWN_HEAVY_AND_RIGHT_LIGHT               = BOX_DRAWINGS_DOWN_HEAVY_AND_RIGHT_LIGHT               ;
		public static readonly char HEAVY_DOWN_AND_RIGHT                     = BOX_DRAWINGS_HEAVY_DOWN_AND_RIGHT                     ;
		public static readonly char LIGHT_DOWN_AND_LEFT                      = BOX_DRAWINGS_LIGHT_DOWN_AND_LEFT                      ;
		public static readonly char DOWN_LIGHT_AND_LEFT_HEAVY                = BOX_DRAWINGS_DOWN_LIGHT_AND_LEFT_HEAVY                ;
		public static readonly char DOWN_HEAVY_AND_LEFT_LIGHT                = BOX_DRAWINGS_DOWN_HEAVY_AND_LEFT_LIGHT                ;
		public static readonly char HEAVY_DOWN_AND_LEFT                      = BOX_DRAWINGS_HEAVY_DOWN_AND_LEFT                      ;
		public static readonly char LIGHT_UP_AND_RIGHT                       = BOX_DRAWINGS_LIGHT_UP_AND_RIGHT                       ;
		public static readonly char UP_LIGHT_AND_RIGHT_HEAVY                 = BOX_DRAWINGS_UP_LIGHT_AND_RIGHT_HEAVY                 ;
		public static readonly char UP_HEAVY_AND_RIGHT_LIGHT                 = BOX_DRAWINGS_UP_HEAVY_AND_RIGHT_LIGHT                 ;
		public static readonly char HEAVY_UP_AND_RIGHT                       = BOX_DRAWINGS_HEAVY_UP_AND_RIGHT                       ;
		public static readonly char LIGHT_UP_AND_LEFT                        = BOX_DRAWINGS_LIGHT_UP_AND_LEFT                        ;
		public static readonly char UP_LIGHT_AND_LEFT_HEAVY                  = BOX_DRAWINGS_UP_LIGHT_AND_LEFT_HEAVY                  ;
		public static readonly char UP_HEAVY_AND_LEFT_LIGHT                  = BOX_DRAWINGS_UP_HEAVY_AND_LEFT_LIGHT                  ;
		public static readonly char HEAVY_UP_AND_LEFT                        = BOX_DRAWINGS_HEAVY_UP_AND_LEFT                        ;
		public static readonly char LIGHT_VERTICAL_AND_RIGHT                 = BOX_DRAWINGS_LIGHT_VERTICAL_AND_RIGHT                 ;
		public static readonly char VERTICAL_LIGHT_AND_RIGHT_HEAVY           = BOX_DRAWINGS_VERTICAL_LIGHT_AND_RIGHT_HEAVY           ;
		public static readonly char UP_HEAVY_AND_RIGHT_DOWN_LIGHT            = BOX_DRAWINGS_UP_HEAVY_AND_RIGHT_DOWN_LIGHT            ;
		public static readonly char DOWN_HEAVY_AND_RIGHT_UP_LIGHT            = BOX_DRAWINGS_DOWN_HEAVY_AND_RIGHT_UP_LIGHT            ;
		public static readonly char VERTICAL_HEAVY_AND_RIGHT_LIGHT           = BOX_DRAWINGS_VERTICAL_HEAVY_AND_RIGHT_LIGHT           ;
		public static readonly char DOWN_LIGHT_AND_RIGHT_UP_HEAVY            = BOX_DRAWINGS_DOWN_LIGHT_AND_RIGHT_UP_HEAVY            ;
		public static readonly char UP_LIGHT_AND_RIGHT_DOWN_HEAVY            = BOX_DRAWINGS_UP_LIGHT_AND_RIGHT_DOWN_HEAVY            ;
		public static readonly char HEAVY_VERTICAL_AND_RIGHT                 = BOX_DRAWINGS_HEAVY_VERTICAL_AND_RIGHT                 ;
		public static readonly char LIGHT_VERTICAL_AND_LEFT                  = BOX_DRAWINGS_LIGHT_VERTICAL_AND_LEFT                  ;
		public static readonly char VERTICAL_LIGHT_AND_LEFT_HEAVY            = BOX_DRAWINGS_VERTICAL_LIGHT_AND_LEFT_HEAVY            ;
		public static readonly char UP_HEAVY_AND_LEFT_DOWN_LIGHT             = BOX_DRAWINGS_UP_HEAVY_AND_LEFT_DOWN_LIGHT             ;
		public static readonly char DOWN_HEAVY_AND_LEFT_UP_LIGHT             = BOX_DRAWINGS_DOWN_HEAVY_AND_LEFT_UP_LIGHT             ;
		public static readonly char VERTICAL_HEAVY_AND_LEFT_LIGHT            = BOX_DRAWINGS_VERTICAL_HEAVY_AND_LEFT_LIGHT            ;
		public static readonly char DOWN_LIGHT_AND_LEFT_UP_HEAVY             = BOX_DRAWINGS_DOWN_LIGHT_AND_LEFT_UP_HEAVY             ;
		public static readonly char UP_LIGHT_AND_LEFT_DOWN_HEAVY             = BOX_DRAWINGS_UP_LIGHT_AND_LEFT_DOWN_HEAVY             ;
		public static readonly char HEAVY_VERTICAL_AND_LEFT                  = BOX_DRAWINGS_HEAVY_VERTICAL_AND_LEFT                  ;
		public static readonly char LIGHT_DOWN_AND_HORIZONTAL                = BOX_DRAWINGS_LIGHT_DOWN_AND_HORIZONTAL                ;
		public static readonly char LEFT_HEAVY_AND_RIGHT_DOWN_LIGHT          = BOX_DRAWINGS_LEFT_HEAVY_AND_RIGHT_DOWN_LIGHT          ;
		public static readonly char RIGHT_HEAVY_AND_LEFT_DOWN_LIGHT          = BOX_DRAWINGS_RIGHT_HEAVY_AND_LEFT_DOWN_LIGHT          ;
		public static readonly char DOWN_LIGHT_AND_HORIZONTAL_HEAVY          = BOX_DRAWINGS_DOWN_LIGHT_AND_HORIZONTAL_HEAVY          ;
		public static readonly char DOWN_HEAVY_AND_HORIZONTAL_LIGHT          = BOX_DRAWINGS_DOWN_HEAVY_AND_HORIZONTAL_LIGHT          ;
		public static readonly char RIGHT_LIGHT_AND_LEFT_DOWN_HEAVY          = BOX_DRAWINGS_RIGHT_LIGHT_AND_LEFT_DOWN_HEAVY          ;
		public static readonly char LEFT_LIGHT_AND_RIGHT_DOWN_HEAVY          = BOX_DRAWINGS_LEFT_LIGHT_AND_RIGHT_DOWN_HEAVY          ;
		public static readonly char HEAVY_DOWN_AND_HORIZONTAL                = BOX_DRAWINGS_HEAVY_DOWN_AND_HORIZONTAL                ;
		public static readonly char LIGHT_UP_AND_HORIZONTAL                  = BOX_DRAWINGS_LIGHT_UP_AND_HORIZONTAL                  ;
		public static readonly char LEFT_HEAVY_AND_RIGHT_UP_LIGHT            = BOX_DRAWINGS_LEFT_HEAVY_AND_RIGHT_UP_LIGHT            ;
		public static readonly char RIGHT_HEAVY_AND_LEFT_UP_LIGHT            = BOX_DRAWINGS_RIGHT_HEAVY_AND_LEFT_UP_LIGHT            ;
		public static readonly char UP_LIGHT_AND_HORIZONTAL_HEAVY            = BOX_DRAWINGS_UP_LIGHT_AND_HORIZONTAL_HEAVY            ;
		public static readonly char UP_HEAVY_AND_HORIZONTAL_LIGHT            = BOX_DRAWINGS_UP_HEAVY_AND_HORIZONTAL_LIGHT            ;
		public static readonly char RIGHT_LIGHT_AND_LEFT_UP_HEAVY            = BOX_DRAWINGS_RIGHT_LIGHT_AND_LEFT_UP_HEAVY            ;
		public static readonly char LEFT_LIGHT_AND_RIGHT_UP_HEAVY            = BOX_DRAWINGS_LEFT_LIGHT_AND_RIGHT_UP_HEAVY            ;
		public static readonly char HEAVY_UP_AND_HORIZONTAL                  = BOX_DRAWINGS_HEAVY_UP_AND_HORIZONTAL                  ;
		public static readonly char LIGHT_VERTICAL_AND_HORIZONTAL            = BOX_DRAWINGS_LIGHT_VERTICAL_AND_HORIZONTAL            ;
		public static readonly char LEFT_HEAVY_AND_RIGHT_VERTICAL_LIGHT      = BOX_DRAWINGS_LEFT_HEAVY_AND_RIGHT_VERTICAL_LIGHT      ;
		public static readonly char RIGHT_HEAVY_AND_LEFT_VERTICAL_LIGHT      = BOX_DRAWINGS_RIGHT_HEAVY_AND_LEFT_VERTICAL_LIGHT      ;
		public static readonly char VERTICAL_LIGHT_AND_HORIZONTAL_HEAVY      = BOX_DRAWINGS_VERTICAL_LIGHT_AND_HORIZONTAL_HEAVY      ;
		public static readonly char UP_HEAVY_AND_DOWN_HORIZONTAL_LIGHT       = BOX_DRAWINGS_UP_HEAVY_AND_DOWN_HORIZONTAL_LIGHT       ;
		public static readonly char DOWN_HEAVY_AND_UP_HORIZONTAL_LIGHT       = BOX_DRAWINGS_DOWN_HEAVY_AND_UP_HORIZONTAL_LIGHT       ;
		public static readonly char VERTICAL_HEAVY_AND_HORIZONTAL_LIGHT      = BOX_DRAWINGS_VERTICAL_HEAVY_AND_HORIZONTAL_LIGHT      ;
		public static readonly char LEFT_UP_HEAVY_AND_RIGHT_DOWN_LIGHT       = BOX_DRAWINGS_LEFT_UP_HEAVY_AND_RIGHT_DOWN_LIGHT       ;
		public static readonly char RIGHT_UP_HEAVY_AND_LEFT_DOWN_LIGHT       = BOX_DRAWINGS_RIGHT_UP_HEAVY_AND_LEFT_DOWN_LIGHT       ;
		public static readonly char LEFT_DOWN_HEAVY_AND_RIGHT_UP_LIGHT       = BOX_DRAWINGS_LEFT_DOWN_HEAVY_AND_RIGHT_UP_LIGHT       ;
		public static readonly char RIGHT_DOWN_HEAVY_AND_LEFT_UP_LIGHT       = BOX_DRAWINGS_RIGHT_DOWN_HEAVY_AND_LEFT_UP_LIGHT       ;
		public static readonly char DOWN_LIGHT_AND_UP_HORIZONTAL_HEAVY       = BOX_DRAWINGS_DOWN_LIGHT_AND_UP_HORIZONTAL_HEAVY       ;
		public static readonly char UP_LIGHT_AND_DOWN_HORIZONTAL_HEAVY       = BOX_DRAWINGS_UP_LIGHT_AND_DOWN_HORIZONTAL_HEAVY       ;
		public static readonly char RIGHT_LIGHT_AND_LEFT_VERTICAL_HEAVY      = BOX_DRAWINGS_RIGHT_LIGHT_AND_LEFT_VERTICAL_HEAVY      ;
		public static readonly char LEFT_LIGHT_AND_RIGHT_VERTICAL_HEAVY      = BOX_DRAWINGS_LEFT_LIGHT_AND_RIGHT_VERTICAL_HEAVY      ;
		public static readonly char HEAVY_VERTICAL_AND_HORIZONTAL            = BOX_DRAWINGS_HEAVY_VERTICAL_AND_HORIZONTAL            ;
		public static readonly char LIGHT_DOUBLE_DASH_HORIZONTAL             = BOX_DRAWINGS_LIGHT_DOUBLE_DASH_HORIZONTAL             ;
		public static readonly char HEAVY_DOUBLE_DASH_HORIZONTAL             = BOX_DRAWINGS_HEAVY_DOUBLE_DASH_HORIZONTAL             ;
		public static readonly char LIGHT_DOUBLE_DASH_VERTICAL               = BOX_DRAWINGS_LIGHT_DOUBLE_DASH_VERTICAL               ;
		public static readonly char HEAVY_DOUBLE_DASH_VERTICAL               = BOX_DRAWINGS_HEAVY_DOUBLE_DASH_VERTICAL               ;
		public static readonly char DOUBLE_HORIZONTAL                        = BOX_DRAWINGS_DOUBLE_HORIZONTAL                        ;
		public static readonly char DOUBLE_VERTICAL                          = BOX_DRAWINGS_DOUBLE_VERTICAL                          ;
		public static readonly char DOWN_SINGLE_AND_RIGHT_DOUBLE             = BOX_DRAWINGS_DOWN_SINGLE_AND_RIGHT_DOUBLE             ;
		public static readonly char DOWN_DOUBLE_AND_RIGHT_SINGLE             = BOX_DRAWINGS_DOWN_DOUBLE_AND_RIGHT_SINGLE             ;
		public static readonly char DOUBLE_DOWN_AND_RIGHT                    = BOX_DRAWINGS_DOUBLE_DOWN_AND_RIGHT                    ;
		public static readonly char DOWN_SINGLE_AND_LEFT_DOUBLE              = BOX_DRAWINGS_DOWN_SINGLE_AND_LEFT_DOUBLE              ;
		public static readonly char DOWN_DOUBLE_AND_LEFT_SINGLE              = BOX_DRAWINGS_DOWN_DOUBLE_AND_LEFT_SINGLE              ;
		public static readonly char DOUBLE_DOWN_AND_LEFT                     = BOX_DRAWINGS_DOUBLE_DOWN_AND_LEFT                     ;
		public static readonly char UP_SINGLE_AND_RIGHT_DOUBLE               = BOX_DRAWINGS_UP_SINGLE_AND_RIGHT_DOUBLE               ;
		public static readonly char UP_DOUBLE_AND_RIGHT_SINGLE               = BOX_DRAWINGS_UP_DOUBLE_AND_RIGHT_SINGLE               ;
		public static readonly char DOUBLE_UP_AND_RIGHT                      = BOX_DRAWINGS_DOUBLE_UP_AND_RIGHT                      ;
		public static readonly char UP_SINGLE_AND_LEFT_DOUBLE                = BOX_DRAWINGS_UP_SINGLE_AND_LEFT_DOUBLE                ;
		public static readonly char UP_DOUBLE_AND_LEFT_SINGLE                = BOX_DRAWINGS_UP_DOUBLE_AND_LEFT_SINGLE                ;
		public static readonly char DOUBLE_UP_AND_LEFT                       = BOX_DRAWINGS_DOUBLE_UP_AND_LEFT                       ;
		public static readonly char VERTICAL_SINGLE_AND_RIGHT_DOUBLE         = BOX_DRAWINGS_VERTICAL_SINGLE_AND_RIGHT_DOUBLE         ;
		public static readonly char VERTICAL_DOUBLE_AND_RIGHT_SINGLE         = BOX_DRAWINGS_VERTICAL_DOUBLE_AND_RIGHT_SINGLE         ;
		public static readonly char DOUBLE_VERTICAL_AND_RIGHT                = BOX_DRAWINGS_DOUBLE_VERTICAL_AND_RIGHT                ;
		public static readonly char VERTICAL_SINGLE_AND_LEFT_DOUBLE          = BOX_DRAWINGS_VERTICAL_SINGLE_AND_LEFT_DOUBLE          ;
		public static readonly char VERTICAL_DOUBLE_AND_LEFT_SINGLE          = BOX_DRAWINGS_VERTICAL_DOUBLE_AND_LEFT_SINGLE          ;
		public static readonly char DOUBLE_VERTICAL_AND_LEFT                 = BOX_DRAWINGS_DOUBLE_VERTICAL_AND_LEFT                 ;
		public static readonly char DOWN_SINGLE_AND_HORIZONTAL_DOUBLE        = BOX_DRAWINGS_DOWN_SINGLE_AND_HORIZONTAL_DOUBLE        ;
		public static readonly char DOWN_DOUBLE_AND_HORIZONTAL_SINGLE        = BOX_DRAWINGS_DOWN_DOUBLE_AND_HORIZONTAL_SINGLE        ;
		public static readonly char DOUBLE_DOWN_AND_HORIZONTAL               = BOX_DRAWINGS_DOUBLE_DOWN_AND_HORIZONTAL               ;
		public static readonly char UP_SINGLE_AND_HORIZONTAL_DOUBLE          = BOX_DRAWINGS_UP_SINGLE_AND_HORIZONTAL_DOUBLE          ;
		public static readonly char UP_DOUBLE_AND_HORIZONTAL_SINGLE          = BOX_DRAWINGS_UP_DOUBLE_AND_HORIZONTAL_SINGLE          ;
		public static readonly char DOUBLE_UP_AND_HORIZONTAL                 = BOX_DRAWINGS_DOUBLE_UP_AND_HORIZONTAL                 ;
		public static readonly char VERTICAL_SINGLE_AND_HORIZONTAL_DOUBLE    = BOX_DRAWINGS_VERTICAL_SINGLE_AND_HORIZONTAL_DOUBLE    ;
		public static readonly char VERTICAL_DOUBLE_AND_HORIZONTAL_SINGLE    = BOX_DRAWINGS_VERTICAL_DOUBLE_AND_HORIZONTAL_SINGLE    ;
		public static readonly char DOUBLE_VERTICAL_AND_HORIZONTAL           = BOX_DRAWINGS_DOUBLE_VERTICAL_AND_HORIZONTAL           ;
		public static readonly char LIGHT_ARC_DOWN_AND_RIGHT                 = BOX_DRAWINGS_LIGHT_ARC_DOWN_AND_RIGHT                 ;
		public static readonly char LIGHT_ARC_DOWN_AND_LEFT                  = BOX_DRAWINGS_LIGHT_ARC_DOWN_AND_LEFT                  ;
		public static readonly char LIGHT_ARC_UP_AND_LEFT                    = BOX_DRAWINGS_LIGHT_ARC_UP_AND_LEFT                    ;
		public static readonly char LIGHT_ARC_UP_AND_RIGHT                   = BOX_DRAWINGS_LIGHT_ARC_UP_AND_RIGHT                   ;
		public static readonly char LIGHT_DIAGONAL_UPPER_RIGHT_TO_LOWER_LEFT = BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_RIGHT_TO_LOWER_LEFT ;
		public static readonly char LIGHT_DIAGONAL_UPPER_LEFT_TO_LOWER_RIGHT = BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_LEFT_TO_LOWER_RIGHT ;
		public static readonly char LIGHT_DIAGONAL_CROSS                     = BOX_DRAWINGS_LIGHT_DIAGONAL_CROSS                     ;
		public static readonly char LIGHT_LEFT                               = BOX_DRAWINGS_LIGHT_LEFT                               ;
		public static readonly char LIGHT_UP                                 = BOX_DRAWINGS_LIGHT_UP                                 ;
		public static readonly char LIGHT_RIGHT                              = BOX_DRAWINGS_LIGHT_RIGHT                              ;
		public static readonly char LIGHT_DOWN                               = BOX_DRAWINGS_LIGHT_DOWN                               ;
		public static readonly char HEAVY_LEFT                               = BOX_DRAWINGS_HEAVY_LEFT                               ;
		public static readonly char HEAVY_UP                                 = BOX_DRAWINGS_HEAVY_UP                                 ;
		public static readonly char HEAVY_RIGHT                              = BOX_DRAWINGS_HEAVY_RIGHT                              ;
		public static readonly char HEAVY_DOWN                               = BOX_DRAWINGS_HEAVY_DOWN                               ;
		public static readonly char LIGHT_LEFT_AND_HEAVY_RIGHT               = BOX_DRAWINGS_LIGHT_LEFT_AND_HEAVY_RIGHT               ;
		public static readonly char LIGHT_UP_AND_HEAVY_DOWN                  = BOX_DRAWINGS_LIGHT_UP_AND_HEAVY_DOWN                  ;
		public static readonly char HEAVY_LEFT_AND_LIGHT_RIGHT               = BOX_DRAWINGS_HEAVY_LEFT_AND_LIGHT_RIGHT               ;
		public static readonly char HEAVY_UP_AND_LIGHT_DOWN                  = BOX_DRAWINGS_HEAVY_UP_AND_LIGHT_DOWN                  ;
	}
}
